// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  attemptSidebar: [{ type: "autogenerated", dirName: "attempt" }],
  webSidebar: [{ type: "autogenerated", dirName: "web" }],
  softwareDesignSidebar: [
    { type: "autogenerated", dirName: "software-design" },
  ],
  hardwareSidebar: [{ type: "autogenerated", dirName: "hardware" }],
  lifeSidebar: [{ type: "autogenerated", dirName: "life" }],
};

module.exports = sidebars;
